# cast_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export CAST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export CAST_VARS_SH="$CAST_DIR/cast_vars.sh"

# Build directories
export CAST_BUILD_DIR="$CAST_DIR/build"
export CAST_SIM_BUILD_DIR="$CAST_BUILD_DIR/simulation"
export CAST_SYNTH_BUILD_DIR="$CAST_BUILD_DIR/synthesis"
export CAST_IMPL_BUILD_DIR="$CAST_BUILD_DIR/implementation"

# Source directories
export CAST_CPP_DIR="$CAST_DIR/cpp"
export CAST_FLIST_DIR="$CAST_DIR/flist"
export CAST_RTL_DIR="$CAST_DIR/rtl"
export CAST_TB_DIR="$CAST_DIR/testbench"
export CAST_SYNTH_DIR="$CAST_DIR/synthesis"
export CAST_IMPL_DIR="$CAST_DIR/implementation"

# C++ model files
export CAST_CPP_HPP="$CAST_CPP_DIR/cast.hpp"
export CAST_CPP_CPP="$CAST_CPP_DIR/cast.cpp"

# RTL files
export CAST_V="$CAST_RTL_DIR/cast.v"

# Testbench files
export CAST_TB_CPP="$CAST_TB_DIR/cast_tb.cpp"
export CAST_TB_HPP="$CAST_TB_DIR/cast_tb.hpp"
export CAST_TB_SV="$CAST_TB_DIR/cast_tb.sv"
export CAST_TB_REGRESSION_JSON="$CAST_TB_DIR/cast_tb_regression.json"

# Backward-compatible alias for simulation regression JSON
export CAST_REGRESSION_JSON="$CAST_TB_REGRESSION_JSON"

# Synthesis files
export CAST_SYNTH_WRAPPER_V="$CAST_SYNTH_DIR/cast_wrapper_synth.v"
export CAST_SYNTH_REGRESSION_JSON="$CAST_SYNTH_DIR/cast_synth_regression.json"

# Implementation files
export CAST_IMPL_WRAPPER_V="$CAST_IMPL_DIR/cast_wrapper_impl.v"
export CAST_IMPL_REGRESSION_JSON="$CAST_IMPL_DIR/cast_impl_regression.json"

# Flists
export CAST_TB_FLIST="$CAST_FLIST_DIR/cast_tb.flist"
export CAST_SYNTH_FLIST="$CAST_FLIST_DIR/cast_synth.flist"
export CAST_IMPL_FLIST="$CAST_FLIST_DIR/cast_impl.flist"

