# ---------- Phantom ----------
N=64
AMP=1.0
PHANTOM=shepp-logan       # {two-disks, rings, two-gaussian-dots, shepp-logan, knee-512}
RINGS_PERIOD=16.0
PHASE0=0.0
PHANTOM_CMAP=gray
# ---------- Aliasing ----------
AF=2                       
AXIS=y                     # x or y
ALIASED_CMAP=gray

# ---------- k-space ----------
KSPACE_CMAP=gray
USE_FFTSHIFT=True     
NORM=ortho                 # backward / ortho / forward / None

# ---------- Sensitivity Maps ----------
L=4
RADIUS_FACTOR=1.0
SIGMA_FACTOR=0.8
PHASE_SCALE=1.0
SMAPS_CMAP=gray