# ---------- Stimulus to apply sense ----------
N=512
PHANTOM=knee-512       # {two-disks, rings, two-gaussian-dots, shepp-logan, knee-512}
AF=2  
L=8
AXIS=y

# ---------- Type of algorithm used in matrix solver ----------
COMPUTE_TYPE=manual-solve            # {numpy-linalg-cholesky, numpy-linalg-solve , manual-solve}