###############################################################################
# Stimulus configuration
###############################################################################

N=64
AF=2
L=4
AXIS="y"
PHANTOM="shepp-logan"
# -------------------- Stimulus visualization --------------------
PHANTOM_CMAP=gray
SMAPS_CMAP=gray
ALIASED_CMAP=gray
KSPACE_CMAP=gray

AMP=1.0
RINGS_PERIOD=16.0
PHASE0=0.0

RADIUS_FACTOR=1.0
SIGMA_FACTOR=0.8
PHASE_SCALE=1.0

USE_FFTSHIFT=True
NORM=ortho

###############################################################################
# Python regression sweep formats
###############################################################################

NB_S_LIST=(16 33)
NBF_S_LIST=(15 32)

NB_K_LIST=(35)
NBF_K_LIST=(32)

NB_A_LIST=(34)
NBF_A_LIST=(32)

NB_B_LIST=(34)
NBF_B_LIST=(32)

###############################################################################
# Selected RTL track format
###############################################################################

TRACK_NB_S=33
TRACK_NBF_S=32

TRACK_NB_Y=35
TRACK_NBF_Y=32

TRACK_NB_A=34
TRACK_NBF_A=32

TRACK_NB_B=34
TRACK_NBF_B=32

###############################################################################
# Division configuration
###############################################################################

# Método de división usado por el modelo Python SENSE
FXP_DIV_METHOD="restoring"          # apy | restoring | newton_raphson
FXP_DIV_QUANT_MODE="trunc"          # trunc | round
FXP_DIV_OVERFLOW="saturate"

# Método de división usado para generar vectores unitarios RTL
TRACK_DIV_METHOD="restoring"        # restoring | newton_raphson
TRACK_DIV_QUANT_MODE="trunc"        # trunc | round
TRACK_DIV_N_CASES=1000
TRACK_DIV_SEED=5678

TRACK_NB_DIV_NUM=16
TRACK_NBF_DIV_NUM=15

TRACK_NB_DIV_DEN=16
TRACK_NBF_DIV_DEN=15

TRACK_NB_DIV_QUOTIENT=16
TRACK_NBF_DIV_QUOTIENT=15


###############################################################################
# RTL synthesis clocks
###############################################################################

CLOCK_AIJ_MHZ=200
CLOCK_BI_MHZ=200
CLOCK_DIV_RESTORING_MHZ=200
CLOCK_DIV_NR_MHZ=200

###############################################################################
# Runtime options
###############################################################################

signed=True
mode=round

MAX_WORKERS=8
CHUNKSIZE=8
SAVE_COMPARISION_IMAGES=False
SNR_DB_THRESHOLD=40