# fft1d_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export FFT1D_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FFT1D_VARS_SH="$FFT1D_DIR/fft1d_vars.sh"

# Build directories
export FFT1D_BUILD_DIR="$FFT1D_DIR/build"
export FFT1D_SIM_BUILD_DIR="$FFT1D_BUILD_DIR/simulation"
export FFT1D_SYNTH_BUILD_DIR="$FFT1D_BUILD_DIR/synthesis"
export FFT1D_IMPL_BUILD_DIR="$FFT1D_BUILD_DIR/implementation"

# Source directories
export FFT1D_CPP_DIR="$FFT1D_DIR/cpp"
export FFT1D_FLIST_DIR="$FFT1D_DIR/flist"
export FFT1D_RTL_DIR="$FFT1D_DIR/rtl"
export FFT1D_TB_DIR="$FFT1D_DIR/testbench"
export FFT1D_SYNTH_DIR="$FFT1D_DIR/synthesis"
export FFT1D_IMPL_DIR="$FFT1D_DIR/implementation"

# C++ model files
export FFT1D_CPP_HPP="$FFT1D_CPP_DIR/fft1d.hpp"
export FFT1D_CPP_CPP="$FFT1D_CPP_DIR/fft1d.cpp"

# RTL files
export FFT1D_V="$FFT1D_RTL_DIR/fft1d.v"

# Testbench files
export FFT1D_TB_CPP="$FFT1D_TB_DIR/fft1d_tb.cpp"
export FFT1D_TB_HPP="$FFT1D_TB_DIR/fft1d_tb.hpp"
export FFT1D_TB_SV="$FFT1D_TB_DIR/fft1d_tb.sv"
export FFT1D_TB_REGRESSION_JSON="$FFT1D_TB_DIR/fft1d_tb_regression.json"

# Backward-compatible alias for simulation regression JSON
export FFT1D_REGRESSION_JSON="$FFT1D_TB_REGRESSION_JSON"

# Synthesis files
export FFT1D_SYNTH_WRAPPER_V="$FFT1D_SYNTH_DIR/fft1d_wrapper_synth.v"
export FFT1D_SYNTH_REGRESSION_JSON="$FFT1D_SYNTH_DIR/fft1d_synth_regression.json"

# Implementation files
export FFT1D_IMPL_WRAPPER_V="$FFT1D_IMPL_DIR/fft1d_wrapper_impl.v"
export FFT1D_IMPL_REGRESSION_JSON="$FFT1D_IMPL_DIR/fft1d_impl_regression.json"

# Flists
export FFT1D_TB_FLIST="$FFT1D_FLIST_DIR/fft1d_tb.flist"
export FFT1D_SYNTH_FLIST="$FFT1D_FLIST_DIR/fft1d_synth.flist"
export FFT1D_IMPL_FLIST="$FFT1D_FLIST_DIR/fft1d_impl.flist"

