# -------------------- Phantom ----------------------
N=512
AMP=1.0
PHANTOM=shepp-logan      # {two-disks, rings, two-gaussian-dots, shepp-logan, knee-512}
PHANTOM_CMAP=gray
RINGS_PERIOD=16.0   #Optional
PHASE0=0.0          #Optional


# -------------------- Stimulus gen --------------------
AF=2        
L=4               
AXIS=y                     # x or y
USE_FFTSHIFT=True     
NORM=ortho                 # backward / ortho / forward / None
RADIUS_FACTOR=1.0   #Optional
SIGMA_FACTOR=0.8    #Optional
PHASE_SCALE=1.0     #Optional
SMAPS_CMAP=gray     #Optional
ALIASED_CMAP=gray   #Optional
KSPACE_CMAP=gray    #Optional


# -------------------- fxp cuantize stimulus and SENSE reconstruction --------------------
NB_LIST=(24 23 22 21 20 19 18 17 16 15 14 13 12)
NBF_LIST=(23 22 21 20 19 18 17 16 15 14 13 12 11)
signed=True
mode=round
CHUNKSIZE=8
MAX_WORKERS=8
SAVE_COMPARISION_IMAGES=True
SNR_DB_THRESHOLD=60




