# tile_transpose_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export TILE_TRANSPOSE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export TILE_TRANSPOSE_VARS_SH="$TILE_TRANSPOSE_DIR/tile_transpose_vars.sh"

# Build directories
export TILE_TRANSPOSE_BUILD_DIR="$TILE_TRANSPOSE_DIR/build"
export TILE_TRANSPOSE_SIM_BUILD_DIR="$TILE_TRANSPOSE_BUILD_DIR/simulation"
export TILE_TRANSPOSE_SYNTH_BUILD_DIR="$TILE_TRANSPOSE_BUILD_DIR/synthesis"
export TILE_TRANSPOSE_IMPL_BUILD_DIR="$TILE_TRANSPOSE_BUILD_DIR/implementation"

# Source directories
export TILE_TRANSPOSE_CPP_DIR="$TILE_TRANSPOSE_DIR/cpp"
export TILE_TRANSPOSE_FLIST_DIR="$TILE_TRANSPOSE_DIR/flist"
export TILE_TRANSPOSE_RTL_DIR="$TILE_TRANSPOSE_DIR/rtl"
export TILE_TRANSPOSE_TB_DIR="$TILE_TRANSPOSE_DIR/testbench"
export TILE_TRANSPOSE_SYNTH_DIR="$TILE_TRANSPOSE_DIR/synthesis"
export TILE_TRANSPOSE_IMPL_DIR="$TILE_TRANSPOSE_DIR/implementation"

# C++ model files
export TILE_TRANSPOSE_CPP_HPP="$TILE_TRANSPOSE_CPP_DIR/tile_transpose.hpp"
export TILE_TRANSPOSE_CPP_CPP="$TILE_TRANSPOSE_CPP_DIR/tile_transpose.cpp"

# RTL files
export TILE_TRANSPOSE_V="$TILE_TRANSPOSE_RTL_DIR/tile_transpose.v"

# Testbench files
export TILE_TRANSPOSE_TB_CPP="$TILE_TRANSPOSE_TB_DIR/tile_transpose_tb.cpp"
export TILE_TRANSPOSE_TB_HPP="$TILE_TRANSPOSE_TB_DIR/tile_transpose_tb.hpp"
export TILE_TRANSPOSE_TB_SV="$TILE_TRANSPOSE_TB_DIR/tile_transpose_tb.sv"
export TILE_TRANSPOSE_TB_REGRESSION_JSON="$TILE_TRANSPOSE_TB_DIR/tile_transpose_tb_regression.json"
export TILE_TRANSPOSE_GTEST_CPP="$TILE_TRANSPOSE/tile_transpose_gtest.cpp"

# Backward-compatible alias for simulation regression JSON
export TILE_TRANSPOSE_REGRESSION_JSON="$TILE_TRANSPOSE_TB_REGRESSION_JSON"

# Synthesis files
export TILE_TRANSPOSE_SYNTH_WRAPPER_V="$TILE_TRANSPOSE_SYNTH_DIR/tile_transpose_wrapper_synth.v"
export TILE_TRANSPOSE_SYNTH_REGRESSION_JSON="$TILE_TRANSPOSE_SYNTH_DIR/tile_transpose_synth_regression.json"

# Implementation files
export TILE_TRANSPOSE_IMPL_WRAPPER_V="$TILE_TRANSPOSE_IMPL_DIR/tile_transpose_wrapper_impl.v"
export TILE_TRANSPOSE_IMPL_REGRESSION_JSON="$TILE_TRANSPOSE_IMPL_DIR/tile_transpose_impl_regression.json"

# Flists
export TILE_TRANSPOSE_TB_FLIST="$TILE_TRANSPOSE_FLIST_DIR/tile_transpose_tb.flist"
export TILE_TRANSPOSE_SYNTH_FLIST="$TILE_TRANSPOSE_FLIST_DIR/tile_transpose_synth.flist"
export TILE_TRANSPOSE_IMPL_FLIST="$TILE_TRANSPOSE_FLIST_DIR/tile_transpose_impl.flist"

