# cmul_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export CMUL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export CMUL_VARS_SH="$CMUL_DIR/cmul_vars.sh"

# Build directories
export CMUL_BUILD_DIR="$CMUL_DIR/build"
export CMUL_SIM_BUILD_DIR="$CMUL_BUILD_DIR/simulation"
export CMUL_SYNTH_BUILD_DIR="$CMUL_BUILD_DIR/synthesis"
export CMUL_IMPL_BUILD_DIR="$CMUL_BUILD_DIR/implementation"

# Source directories
export CMUL_CPP_DIR="$CMUL_DIR/cpp"
export CMUL_FLIST_DIR="$CMUL_DIR/flist"
export CMUL_RTL_DIR="$CMUL_DIR/rtl"
export CMUL_TB_DIR="$CMUL_DIR/testbench"
export CMUL_SYNTH_DIR="$CMUL_DIR/synthesis"
export CMUL_IMPL_DIR="$CMUL_DIR/implementation"

# C++ model files
export CMUL_CPP_HPP="$CMUL_CPP_DIR/cmul.hpp"
export CMUL_CPP_CPP="$CMUL_CPP_DIR/cmul.cpp"

# RTL files
export CMUL_V="$CMUL_RTL_DIR/cmul.v"

# Testbench files
export CMUL_TB_CPP="$CMUL_TB_DIR/cmul_tb.cpp"
export CMUL_TB_HPP="$CMUL_TB_DIR/cmul_tb.hpp"
export CMUL_TB_SV="$CMUL_TB_DIR/cmul_tb.sv"
export CMUL_TB_REGRESSION_JSON="$CMUL_TB_DIR/cmul_tb_regression.json"

# Backward-compatible alias for simulation regression JSON
export CMUL_REGRESSION_JSON="$CMUL_TB_REGRESSION_JSON"

# Synthesis files
export CMUL_SYNTH_WRAPPER_V="$CMUL_SYNTH_DIR/cmul_wrapper_synth.v"
export CMUL_SYNTH_REGRESSION_JSON="$CMUL_SYNTH_DIR/cmul_synth_regression.json"

# Implementation files
export CMUL_IMPL_WRAPPER_V="$CMUL_IMPL_DIR/cmul_wrapper_impl.v"
export CMUL_IMPL_REGRESSION_JSON="$CMUL_IMPL_DIR/cmul_impl_regression.json"

# Flists
export CMUL_TB_FLIST="$CMUL_FLIST_DIR/cmul_tb.flist"
export CMUL_SYNTH_FLIST="$CMUL_FLIST_DIR/cmul_synth.flist"
export CMUL_IMPL_FLIST="$CMUL_FLIST_DIR/cmul_impl.flist"

