#!/usr/bin/env bash

# Este archivo debe ser sourced desde set_env.sh.

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "[constraint_utils.sh] ERROR: this file must be sourced, not executed." >&2
    exit 1
fi

constraint_log() {
    echo "[constraint_utils.sh] $*"
}

constraint_error() {
    echo "[constraint_utils.sh] ERROR: $*" >&2
}

constraint_require_env() {
    local name="$1"

    if [[ -z "${!name:-}" ]]; then
        constraint_error "environment variable not defined: $name"
        return 1
    fi
}

constraint_module_prefix() {
    local module_name="$1"

    if declare -F module_prefix >/dev/null 2>&1; then
        module_prefix "$module_name"
    else
        echo "$module_name" | tr '[:lower:]' '[:upper:]'
    fi
}

constraint_detect_current_module() {
    constraint_require_env MODULES_ROOT || return 1

    local pwd_real
    local modules_real
    local rel_path
    local module_name

    pwd_real="$(pwd -P)"
    modules_real="$(cd "$MODULES_ROOT" && pwd -P)" || return 1

    case "$pwd_real" in
        "$modules_real"/*)
            rel_path="${pwd_real#$modules_real/}"
            module_name="${rel_path%%/*}"
            ;;
        *)
            constraint_error "current directory is not inside MODULES_ROOT."
            echo "[constraint_utils.sh]        pwd=$pwd_real" >&2
            echo "[constraint_utils.sh]        MODULES_ROOT=$modules_real" >&2
            return 1
            ;;
    esac

    if [[ -z "$module_name" ]]; then
        constraint_error "could not detect current module."
        return 1
    fi

    if [[ ! -d "$MODULES_ROOT/$module_name" ]]; then
        constraint_error "detected module directory does not exist: $MODULES_ROOT/$module_name"
        return 1
    fi

    printf "%s\n" "$module_name"
}

constraint_get_module_var() {
    local var_name="$1"

    if [[ -z "${!var_name:-}" ]]; then
        constraint_error "variable not defined: $var_name"
        return 1
    fi

    printf "%s\n" "${!var_name}"
}

constraint_get_conf_var() {
    local var_name="$1"
    local default_value="${2:-}"

    if [[ -n "${!var_name:-}" ]]; then
        printf "%s\n" "${!var_name}"
    else
        printf "%s\n" "$default_value"
    fi
}

constraint_is_positive_number() {
    local value="$1"

    [[ "$value" =~ ^([0-9]+([.][0-9]*)?|[.][0-9]+)$ ]] || return 1

    awk -v v="$value" 'BEGIN { exit !(v > 0.0) }'
}

constraint_freq_to_period_ns() {
    local freq_mhz="$1"

    awk -v f="$freq_mhz" 'BEGIN { printf "%.6f", 1000.0 / f }'
}

constraint_update_managed_block() {
    local file="$1"
    local begin_marker="$2"
    local end_marker="$3"
    local block_file="$4"

    local tmp_file
    tmp_file="$(mktemp)" || return 1

    mkdir -p "$(dirname "$file")"
    touch "$file"

    awk \
        -v begin="$begin_marker" \
        -v end="$end_marker" \
        '
        $0 == begin { skip = 1; next }
        $0 == end   { skip = 0; next }
        skip == 0   { print }
        ' "$file" > "$tmp_file"

    {
        cat "$tmp_file"

        if [[ -s "$tmp_file" ]]; then
            echo
        fi

        cat "$block_file"
    } > "$file"

    rm -f "$tmp_file"
}

constraint_write_clock_block() {
    local block_file="$1"
    local module_name="$2"
    local clock_period_ns="$3"
    local clock_uncertainty_ns="$4"

    cat > "$block_file" <<EOF
# >>> AUTO_CLOCK_CONSTRAINTS BEGIN
# Generated by update_constraints.
# Do not edit inside this managed block.
#
# Module      : $module_name
# Clock name  : i_clock
# Clock port  : i_clock
# Period [ns] : $clock_period_ns

create_clock -name {i_clock} -period $clock_period_ns [get_ports {i_clock}]
EOF

    if [[ -n "$clock_uncertainty_ns" ]]; then
        cat >> "$block_file" <<EOF
set_clock_uncertainty $clock_uncertainty_ns [get_clocks {i_clock}]
EOF
    fi

    cat >> "$block_file" <<EOF
# <<< AUTO_CLOCK_CONSTRAINTS END
EOF
}

update_constraints() {
    if [[ "$#" -ne 0 ]]; then
        constraint_error "usage: update_constraints"
        constraint_error "       run it from inside modules/<module_name>/..."
        return 1
    fi

    constraint_require_env MODULES_ROOT || return 1

    local module_name
    module_name="$(constraint_detect_current_module)" || return 1

    if [[ ! "$module_name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
        constraint_error "invalid detected module name: $module_name"
        return 1
    fi

    local prefix
    prefix="$(constraint_module_prefix "$module_name")"

    local module_dir="$MODULES_ROOT/$module_name"
    local vars_file="$module_dir/${module_name}_vars.sh"

    if [[ ! -f "$vars_file" ]]; then
        constraint_error "missing vars file: $vars_file"
        return 1
    fi

    source "$vars_file"


    # Variables genéricas del .conf.
    # Se limpian antes de sourcear para evitar arrastrar valores de otro módulo.
    unset CLOCK_PERIOD_NS
    unset CLOCK_FREQ_MHZ
    unset CLOCK_UNCERTAINTY_NS

    source "$conf_file"

    local clock_period_ns
    local clock_freq_mhz
    local clock_uncertainty_ns

    clock_period_ns="$(constraint_get_conf_var "CLOCK_PERIOD_NS" "")"
    clock_freq_mhz="$(constraint_get_conf_var "CLOCK_FREQ_MHZ" "")"
    clock_uncertainty_ns="$(constraint_get_conf_var "CLOCK_UNCERTAINTY_NS" "")"

    if [[ -z "$clock_period_ns" && -z "$clock_freq_mhz" ]]; then
        constraint_error "define either CLOCK_PERIOD_NS or CLOCK_FREQ_MHZ in $conf_file"
        return 1
    fi

    if [[ -n "$clock_period_ns" && -n "$clock_freq_mhz" ]]; then
        constraint_error "define only one of CLOCK_PERIOD_NS or CLOCK_FREQ_MHZ in $conf_file"
        return 1
    fi

    if [[ -n "$clock_freq_mhz" ]]; then
        if ! constraint_is_positive_number "$clock_freq_mhz"; then
            constraint_error "invalid CLOCK_FREQ_MHZ=$clock_freq_mhz"
            return 1
        fi

        clock_period_ns="$(constraint_freq_to_period_ns "$clock_freq_mhz")"
    fi

    if ! constraint_is_positive_number "$clock_period_ns"; then
        constraint_error "invalid CLOCK_PERIOD_NS=$clock_period_ns"
        return 1
    fi

    if [[ -n "$clock_uncertainty_ns" ]]; then
        if ! constraint_is_positive_number "$clock_uncertainty_ns"; then
            constraint_error "invalid CLOCK_UNCERTAINTY_NS=$clock_uncertainty_ns"
            return 1
        fi
    fi

    local block_file
    block_file="$(mktemp)" || return 1

    constraint_write_clock_block \
        "$block_file" \
        "$module_name" \
        "$clock_period_ns" \
        "$clock_uncertainty_ns"

    constraint_update_managed_block \
        "$synth_xdc" \
        "# >>> AUTO_CLOCK_CONSTRAINTS BEGIN" \
        "# <<< AUTO_CLOCK_CONSTRAINTS END" \
        "$block_file"

    constraint_update_managed_block \
        "$impl_xdc" \
        "# >>> AUTO_CLOCK_CONSTRAINTS BEGIN" \
        "# <<< AUTO_CLOCK_CONSTRAINTS END" \
        "$block_file"

    rm -f "$block_file"

    constraint_log "module      : $module_name"
    constraint_log "conf        : $conf_file"
    constraint_log "clock_port  : i_clock"
    constraint_log "clock_name  : i_clock"
    constraint_log "period_ns   : $clock_period_ns"

    if [[ -n "$clock_freq_mhz" ]]; then
        constraint_log "freq_mhz    : $clock_freq_mhz"
    fi

    if [[ -n "$clock_uncertainty_ns" ]]; then
        constraint_log "uncertainty : $clock_uncertainty_ns"
    fi

    constraint_log "updated     : $synth_xdc"
    constraint_log "updated     : $impl_xdc"
}