#!/usr/bin/env bash

# Este archivo debe ser sourced desde set_env.sh.

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "[module_utils.sh] ERROR: this file must be sourced, not executed." >&2
    exit 1
fi

module_utils_log() {
    echo "[module_utils.sh] $*"
}

module_utils_error() {
    echo "[module_utils.sh] ERROR: $*" >&2
}

module_utils_require_env() {
    local name="$1"

    if [[ -z "${!name:-}" ]]; then
        module_utils_error "environment variable not defined: $name"
        return 1
    fi
}

module_prefix() {
    local name="$1"
    echo "$name" | tr '[:lower:]' '[:upper:]'
}

validate_module_name() {
    local module_name="$1"

    if [[ -z "$module_name" ]]; then
        module_utils_error "usage: create_module <module_name>"
        return 1
    fi

    if [[ ! "$module_name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
        module_utils_error "invalid module name: $module_name"
        return 1
    fi
}

source_module_vars() {
    module_utils_require_env MODULES_ROOT || return 1

    local vars_file

    shopt -s nullglob
    for vars_file in "$MODULES_ROOT"/*/*_vars.sh; do
        source "$vars_file"
    done
    shopt -u nullglob
}

write_module_vars_file() {
    local module_name="$1"
    local prefix="$2"
    local variables_file="$3"

    cat > "$variables_file" <<EOF
# ${module_name}_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export ${prefix}_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
export ${prefix}_VARS_SH="\$${prefix}_DIR/${module_name}_vars.sh"

# Build directories
export ${prefix}_BUILD_DIR="\$${prefix}_DIR/build"
export ${prefix}_SIM_BUILD_DIR="\$${prefix}_BUILD_DIR/simulation"
export ${prefix}_SYNTH_BUILD_DIR="\$${prefix}_BUILD_DIR/synthesis"
export ${prefix}_IMPL_BUILD_DIR="\$${prefix}_BUILD_DIR/implementation"

# Source directories
export ${prefix}_CPP_DIR="\$${prefix}_DIR/cpp"
export ${prefix}_FLIST_DIR="\$${prefix}_DIR/flist"
export ${prefix}_RTL_DIR="\$${prefix}_DIR/rtl"
export ${prefix}_TB_DIR="\$${prefix}_DIR/testbench"
export ${prefix}_SYNTH_DIR="\$${prefix}_DIR/synthesis"
export ${prefix}_IMPL_DIR="\$${prefix}_DIR/implementation"

# C++ model files
export ${prefix}_CPP_HPP="\$${prefix}_CPP_DIR/${module_name}.hpp"
export ${prefix}_CPP_CPP="\$${prefix}_CPP_DIR/${module_name}.cpp"

# RTL files
export ${prefix}_V="\$${prefix}_RTL_DIR/${module_name}.v"

# Testbench files
export ${prefix}_TB_CPP="\$${prefix}_TB_DIR/${module_name}_tb.cpp"
export ${prefix}_TB_HPP="\$${prefix}_TB_DIR/${module_name}_tb.hpp"
export ${prefix}_TB_SV="\$${prefix}_TB_DIR/${module_name}_tb.sv"
export ${prefix}_TB_REGRESSION_JSON="\$${prefix}_TB_DIR/${module_name}_tb_regression.json"
export ${prefix}_GTEST_CPP="\$${prefix}/${module_name}_gtest.cpp"

# Backward-compatible alias for simulation regression JSON
export ${prefix}_REGRESSION_JSON="\$${prefix}_TB_REGRESSION_JSON"

# Synthesis files
export ${prefix}_SYNTH_WRAPPER_V="\$${prefix}_SYNTH_DIR/${module_name}_wrapper_synth.v"
export ${prefix}_SYNTH_REGRESSION_JSON="\$${prefix}_SYNTH_DIR/${module_name}_synth_regression.json"

# Implementation files
export ${prefix}_IMPL_WRAPPER_V="\$${prefix}_IMPL_DIR/${module_name}_wrapper_impl.v"
export ${prefix}_IMPL_REGRESSION_JSON="\$${prefix}_IMPL_DIR/${module_name}_impl_regression.json"

# Flists
export ${prefix}_TB_FLIST="\$${prefix}_FLIST_DIR/${module_name}_tb.flist"
export ${prefix}_SYNTH_FLIST="\$${prefix}_FLIST_DIR/${module_name}_synth.flist"
export ${prefix}_IMPL_FLIST="\$${prefix}_FLIST_DIR/${module_name}_impl.flist"

EOF
}

write_default_sim_regression_json() {
    local json_file="$1"

    if [[ -s "$json_file" ]]; then
        return 0
    fi

    cat > "$json_file" <<EOF
{
  "regression_dir": "build",
  "defaults": {
    "N_CYCLES": 16,
    "auto_defines": true
  },
  "cases": []
}
EOF
}

write_default_synth_regression_json() {
    local json_file="$1"

    if [[ -s "$json_file" ]]; then
        return 0
    fi

    cat > "$json_file" <<EOF
{
  "regression_dir": "build/synthesis",
  "defaults": {
    "PART_NAME": "xck26-sfvc784-2LV-c",
    "CLOCK_PERIOD_NS": 5.000,
    "CLOCK_UNCERTAINTY_NS": 0.05
  },
  "cases": []
}
EOF
}

write_default_impl_regression_json() {
    local json_file="$1"

    if [[ -s "$json_file" ]]; then
        return 0
    fi

    cat > "$json_file" <<EOF
{
  "regression_dir": "build/implementation",
  "defaults": {
    "PART_NAME": "xck26-sfvc784-2LV-c",
    "CLOCK_PERIOD_NS": 5.000,
    "CLOCK_UNCERTAINTY_NS": 0.05
  },
  "cases": []
}
EOF
}

create_module_dirs() {
    local module_dir="$1"

    mkdir -p "$module_dir/build"

    mkdir -p "$module_dir/cpp"
    mkdir -p "$module_dir/flist"
    mkdir -p "$module_dir/rtl"
    mkdir -p "$module_dir/testbench"
    mkdir -p "$module_dir/synthesis"
    mkdir -p "$module_dir/implementation"
}

write_file_if_empty() {
    local file="$1"

    if [[ -s "$file" ]]; then
        return 0
    fi

    mkdir -p "$(dirname "$file")"
    cat > "$file"
}
write_impl_wrapper_template() {
    local module_name="$1"
    local module_dir="$2"

    write_file_if_empty "$module_dir/implementation/${module_name}_wrapper_impl.v" <<EOF
\`default_nettype none

/*
 * Wrapper de implementación para ${module_name}.
 *
 * Puede ser equivalente al wrapper de síntesis, cambiando el nombre del top.
 */
module ${module_name}_wrapper_impl (
    input wire i_clock
);

    // Implement implementation wrapper

endmodule

\`default_nettype wire
EOF
}
write_synth_wrapper_template() {
    local module_name="$1"
    local module_dir="$2"

    write_file_if_empty "$module_dir/synthesis/${module_name}_wrapper_synth.v" <<EOF
\`default_nettype none

/*
 * Synthesis wrapper for ${module_name}.
 *
 * Recomendación:
 * - registrar entradas
 * - instanciar el DUT
 * - registrar salidas
 * - exponer i_clock
 */
module ${module_name}_wrapper_synth (
    input wire i_clock
);

    // Implement synthesis wrapper

endmodule

\`default_nettype wire
EOF
}
write_rtl_template() {
    local module_name="$1"
    local module_dir="$2"

    write_file_if_empty "$module_dir/rtl/${module_name}.v" <<EOF
\`timescale 1ns/1ps
\`default_nettype none

/*
 * Implement RTL for ${module_name}.
 */
module ${module_name}();

endmodule

\`default_nettype wire
EOF
}
write_tb_sv_template() {
    local module_name="$1"
    local module_dir="$2"

    write_file_if_empty "$module_dir/testbench/${module_name}_tb.sv" <<EOF
\`timescale 1ns/1ps
\`default_nettype none

module ${module_name}_tb;

    initial begin
        \$display("[${module_name}_tb] Implement SystemVerilog testbench.");
        \$finish;
    end

endmodule

\`default_nettype wire
EOF
}
write_tb_cpp_template() {
    local module_name="$1"
    local module_dir="$2"

    write_file_if_empty "$module_dir/testbench/${module_name}_tb.cpp" <<EOF
#include "${module_name}_tb.hpp"

#include "rtlsim.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>

namespace fs = std::filesystem;

namespace ${module_name}_tb {

tb_args parse_args(int argc, char** argv)
{
    tb_args args;

    for (int i = 1; i < argc; ++i) {
        const std::string key = argv[i];

        if (key == "--case-dir") {
            if (++i >= argc) {
                throw std::runtime_error("missing value for --case-dir");
            }

            args.case_dir = argv[i];
        }
        else if (key == "--n-cycles" || key == "--N_CYCLES") {
            if (++i >= argc) {
                throw std::runtime_error("missing value for " + key);
            }

            args.n_cycles = std::stoi(argv[i]);
        }
        else {
            throw std::runtime_error("unknown argument: " + key);
        }
    }

    return args;
}

void run_tb(const tb_args& args)
{
    /*
     * Expected case layout:
     *
     *   build/<CASE>/
     *     binary/
     *     simulation/
     *       vectors/
     *         stimuli/
     *           in_ports.csv
     *           in_ports/
     *             <input_signal>.dat
     *         expected/
     *           out_ports.csv
     *           out_ports/
     *             <output_signal>.dat
     *     reports/
     *       vm_summary.rpt
     */

    const fs::path sim_dir      = args.case_dir / "simulation";
    const fs::path vectors_dir  = sim_dir / "vectors";
    const fs::path stimuli_dir  = vectors_dir / "stimuli";
    const fs::path expected_dir = vectors_dir / "expected";
    const fs::path reports_dir  = args.case_dir / "reports";

    const fs::path in_dat_dir  = stimuli_dir / "in_ports";
    const fs::path out_dat_dir = expected_dir / "out_ports";

    fs::create_directories(stimuli_dir);
    fs::create_directories(expected_dir);
    fs::create_directories(in_dat_dir);
    fs::create_directories(out_dat_dir);
    fs::create_directories(reports_dir);

    std::ofstream report_file(reports_dir / "vm_summary.rpt");

    if (!report_file) {
        throw std::runtime_error("could not open report file");
    }

    rtl::ClockDomain clk;
    ${module_name}::${module_name}_model dut;
    rtl::Simulator sim(clk);

    sim.add(dut);
    sim.init();

    /*
     * CSV + DAT traces.
     *
     * These files are used by run_regression_sim.py:
     *
     *   stimuli/in_ports.csv
     *   stimuli/in_ports/<signal>.dat
     *
     *   expected/out_ports.csv
     *   expected/out_ports/<signal>.dat
     *
     * The generic template only writes the cycle column in the CSV files.
     * Add module-specific ports below when the model defines them.
     */

    rtl::CsvDatTrace in_ports_trace(
        (stimuli_dir / "in_ports.csv").string(),
        in_dat_dir.string()
    );

    rtl::CsvDatTrace out_ports_trace(
        (expected_dir / "out_ports.csv").string(),
        out_dat_dir.string()
    );

    /*
     * Input port trace examples:
     *
     * in_ports_trace.add_value("i_en", [&dut]() {
     *     return rtl::value_to_string(dut.i_en.value());
     * });
     *
     * in_ports_trace.add_value("i_word", [&dut]() {
     *     return rtl::value_to_string(dut.i_word.value());
     * });
     */

    /*
     * Output port trace examples:
     *
     * out_ports_trace.add_value("o_en", [&dut]() {
     *     return rtl::value_to_string(dut.o_en.value());
     * });
     *
     * out_ports_trace.add_value("o_word", [&dut]() {
     *     return rtl::value_to_string(dut.o_word.value());
     * });
     */

    for (int cycle = 0; cycle < args.n_cycles; ++cycle) {
        /*
         * Drive module-specific inputs here.
         *
         * Example:
         *
         * dut.i_en   = true;
         * dut.i_word = input_value;
         */

        sim.cycle();

        in_ports_trace.sample(sim.cycle_count());
        out_ports_trace.sample(sim.cycle_count());
    }

    report_file << "VM SUMMARY\\n";
    report_file << "==========\\n\\n";
    report_file << "module      : ${module_name}\\n";
    report_file << "case_dir    : " << args.case_dir << "\\n";
    report_file << "n_cycles    : " << args.n_cycles << "\\n";
    report_file << "cycles      : " << sim.cycle_count() << "\\n";
    report_file << "\\n";
    report_file << "input_csv   : " << (stimuli_dir / "in_ports.csv") << "\\n";
    report_file << "output_csv  : " << (expected_dir / "out_ports.csv") << "\\n";
    report_file << "input_dat   : " << in_dat_dir << "\\n";
    report_file << "output_dat  : " << out_dat_dir << "\\n";
}

} // namespace ${module_name}_tb

int main(int argc, char** argv)
{
    try {
        const auto args = ${module_name}_tb::parse_args(argc, argv);
        ${module_name}_tb::run_tb(args);
        return 0;
    }
    catch (const std::exception& e) {
        std::cerr << "[${module_name}_tb] ERROR: " << e.what() << "\\n";
        return 1;
    }
}
EOF
}
write_tb_hpp_template() {
    local module_name="$1"
    local module_dir="$2"

    write_file_if_empty "$module_dir/testbench/${module_name}_tb.hpp" <<EOF
#pragma once

#include "../cpp/${module_name}.hpp"

#include <filesystem>

namespace ${module_name}_tb {

struct tb_args {
    std::filesystem::path case_dir {"."};
    int n_cycles {16};
};

tb_args parse_args(int argc, char** argv);
void run_tb(const tb_args& args);

} // namespace ${module_name}_tb
EOF
}
write_cpp_cpp_template() {
    local module_name="$1"
    local module_dir="$2"

    write_file_if_empty "$module_dir/cpp/${module_name}.cpp" <<EOF
#include "${module_name}.hpp"

namespace ${module_name} {

void ${module_name}_model::connect_clocks(rtl::ClockDomain& clk)
{
    (void)clk;

    /*
     * Add sequential state/registers to the clock domain.
     *
     * Example:
     *
     * clk.add(valid_r);
     * clk.add(y_r);
     */
}

void ${module_name}_model::init()
{
    /*
     * Initialize ports, wires and registers.
     *
     * Example:
     *
     * i_en   = false;
     * i_word = in_t {};
     *
     * o_en   = false;
     * o_word = out_t {};
     *
     * y_w = out_t {};
     *
     * valid_r.set_initial_value(false);
     * y_r.set_initial_value(out_t {});
     */
}

void ${module_name}_model::combinational()
{
    /*
     * Describe combinational behavior.
     *
     * Example:
     *
     * y_w = out_t(i_word.value());
     *
     * o_en   = valid_r.o;
     * o_word = y_r.o;
     */
}

void ${module_name}_model::sequential()
{
    /*
     * Describe clocked behavior.
     *
     * Important:
     * - Assign next register values using reg.i
     * - Read current register values using reg.o
     *
     * Example:
     *
     * valid_r.i = i_en.value();
     *
     * if (i_en.value()) {
     *     y_r.i = y_w.value();
     * }
     * else {
     *     y_r.i = y_r.o;
     * }
     */
}

} // namespace ${module_name}
EOF
}
write_cpp_hpp_template() {
    local module_name="$1"
    local module_dir="$2"
    local prefix

    prefix="$(module_prefix "$module_name")"

    write_file_if_empty "$module_dir/cpp/${module_name}.hpp" <<EOF
#pragma once

#include "rtlsim.hpp"

#include <ap_fixed.h>
#include <cstdint>

namespace ${module_name} {

/*
 * --------------------------------------------------------------------------
 * Parameters
 * --------------------------------------------------------------------------
 *
 * These values are equivalent to Verilog parameters.
 * They may be overridden from the build system using compiler defines.
 *
 * Example:
 *
 * #ifndef ${prefix}_NB_IN
 * #define ${prefix}_NB_IN 16
 * #endif
 *
 * #ifndef ${prefix}_NBF_IN
 * #define ${prefix}_NBF_IN 14
 * #endif
 *
 * #ifndef ${prefix}_NB_OUT
 * #define ${prefix}_NB_OUT 16
 * #endif
 *
 * #ifndef ${prefix}_NBF_OUT
 * #define ${prefix}_NBF_OUT 14
 * #endif
 */

enum parameters : int {
    /*
     * Example:
     *
     * NB_IN   = ${prefix}_NB_IN,
     * NBF_IN  = ${prefix}_NBF_IN,
     * NB_OUT  = ${prefix}_NB_OUT,
     * NBF_OUT = ${prefix}_NBF_OUT
     */
};

/*
 * --------------------------------------------------------------------------
 * Localparameters
 * --------------------------------------------------------------------------
 *
 * These values are equivalent to Verilog localparams.
 * They are derived from parameters and must not be overridden externally.
 */

enum localparameters : int {
    /*
     * Example:
     *
     * NBI_IN  = NB_IN  - NBF_IN,
     * NBI_OUT = NB_OUT - NBF_OUT
     */
};

/*
 * --------------------------------------------------------------------------
 * Data types
 * --------------------------------------------------------------------------
 *
 * ap_fixed standard convention:
 *   ap_fixed<W, I>
 *   W = total width
 *   I = integer bits, sign included
 *
 * Example:
 *
 * using bit_t = bool;
 * using in_t  = ap_fixed<NB_IN,  NBI_IN>;
 * using out_t = ap_fixed<NB_OUT, NBI_OUT>;
 */

class ${module_name}_model final : public rtl::Module {
public:
    ${module_name}_model() = default;

    /*
     * ----------------------------------------------------------------------
     * Ports
     * ----------------------------------------------------------------------
     *
     * Example:
     *
     * rtl::InPort<bit_t> i_en;
     * rtl::InPort<in_t>  i_word;
     *
     * rtl::OutPort<bit_t> o_en;
     * rtl::OutPort<out_t> o_word;
     */

    /*
     * ----------------------------------------------------------------------
     * Internal wires/registers
     * ----------------------------------------------------------------------
     *
     * Example:
     *
     * rtl::Wire<out_t> y_w;
     *
     * rtl::Reg<bit_t> valid_r;
     * rtl::Reg<out_t> y_r;
     */

    void connect_clocks(rtl::ClockDomain& clk) override;
    void init() override;
    void combinational() override;
    void sequential() override;

private:

};

} // namespace ${module_name}
EOF
}


create_module_files() {
    local module_name="$1"
    local module_dir="$2"

    # C++ model
    write_cpp_hpp_template "$module_name" "$module_dir"
    write_cpp_cpp_template "$module_name" "$module_dir"

    # RTL
    write_rtl_template "$module_name" "$module_dir"

    # Testbench
    write_tb_hpp_template "$module_name" "$module_dir"
    write_tb_cpp_template "$module_name" "$module_dir"
    write_tb_sv_template "$module_name" "$module_dir"

    write_default_sim_regression_json \
        "$module_dir/testbench/${module_name}_tb_regression.json"

    # Synthesis
    write_synth_wrapper_template "$module_name" "$module_dir"
    write_default_synth_regression_json \
        "$module_dir/synthesis/${module_name}_synth_regression.json"

    # Implementation
    write_impl_wrapper_template "$module_name" "$module_dir"
    write_default_impl_regression_json \
        "$module_dir/implementation/${module_name}_impl_regression.json"

    # Flists
    touch "$module_dir/flist/${module_name}_tb.flist"
    touch "$module_dir/flist/${module_name}_synth.flist"
    touch "$module_dir/flist/${module_name}_impl.flist"
}

create_module() {
    local module_name="${1:-}"

    module_utils_require_env MODULES_ROOT || return 1
    validate_module_name "$module_name" || return 1

    local prefix
    prefix="$(module_prefix "$module_name")"

    local module_dir="$MODULES_ROOT/$module_name"
    local variables_file="$module_dir/${module_name}_vars.sh"

    create_module_dirs "$module_dir"

    if [[ ! -f "$variables_file" ]]; then
        write_module_vars_file "$module_name" "$prefix" "$variables_file"
        module_utils_log "created vars file: $variables_file"
    else
        module_utils_log "vars file already exists: $variables_file"
    fi

    create_module_files "$module_name" "$module_dir"

    source "$variables_file"

    module_utils_log "module created: $module_dir"
}

refresh_module_vars() {
    local module_name="${1:-}"

    module_utils_require_env MODULES_ROOT || return 1
    validate_module_name "$module_name" || return 1

    local prefix
    prefix="$(module_prefix "$module_name")"

    local module_dir="$MODULES_ROOT/$module_name"
    local variables_file="$module_dir/${module_name}_vars.sh"

    if [[ ! -d "$module_dir" ]]; then
        module_utils_error "module does not exist: $module_dir"
        return 1
    fi

    write_module_vars_file "$module_name" "$prefix" "$variables_file"
    source "$variables_file"

    module_utils_log "refreshed vars file: $variables_file"
}

cd_module() {
    local module_name="${1:-}"

    module_utils_require_env MODULES_ROOT || return 1

    if [[ -z "$module_name" ]]; then
        module_utils_error "usage: cd_module <module_name>"
        return 1
    fi

    if [[ ! -d "$MODULES_ROOT/$module_name" ]]; then
        module_utils_error "module does not exist: $MODULES_ROOT/$module_name"
        return 1
    fi

    cd "$MODULES_ROOT/$module_name" || return 1
}

list_modules() {
    module_utils_require_env MODULES_ROOT || return 1

    find "$MODULES_ROOT" \
        -mindepth 1 \
        -maxdepth 1 \
        -type d \
        -printf "%f\n" 2>/dev/null | sort
}