# cmul_karatsuba_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export CMUL_KARATSUBA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export CMUL_KARATSUBA_VARS_SH="$CMUL_KARATSUBA_DIR/cmul_karatsuba_vars.sh"

# Build directories
export CMUL_KARATSUBA_BUILD_DIR="$CMUL_KARATSUBA_DIR/build"
export CMUL_KARATSUBA_SIM_BUILD_DIR="$CMUL_KARATSUBA_BUILD_DIR/simulation"
export CMUL_KARATSUBA_SYNTH_BUILD_DIR="$CMUL_KARATSUBA_BUILD_DIR/synthesis"
export CMUL_KARATSUBA_IMPL_BUILD_DIR="$CMUL_KARATSUBA_BUILD_DIR/implementation"

# Source directories
export CMUL_KARATSUBA_CPP_DIR="$CMUL_KARATSUBA_DIR/cpp"
export CMUL_KARATSUBA_FLIST_DIR="$CMUL_KARATSUBA_DIR/flist"
export CMUL_KARATSUBA_RTL_DIR="$CMUL_KARATSUBA_DIR/rtl"
export CMUL_KARATSUBA_TB_DIR="$CMUL_KARATSUBA_DIR/testbench"
export CMUL_KARATSUBA_SYNTH_DIR="$CMUL_KARATSUBA_DIR/synthesis"
export CMUL_KARATSUBA_IMPL_DIR="$CMUL_KARATSUBA_DIR/implementation"

# C++ model files
export CMUL_KARATSUBA_CPP_HPP="$CMUL_KARATSUBA_CPP_DIR/cmul_karatsuba.hpp"
export CMUL_KARATSUBA_CPP_CPP="$CMUL_KARATSUBA_CPP_DIR/cmul_karatsuba.cpp"

# RTL files
export CMUL_KARATSUBA_V="$CMUL_KARATSUBA_RTL_DIR/cmul_karatsuba.v"

# Testbench files
export CMUL_KARATSUBA_TB_CPP="$CMUL_KARATSUBA_TB_DIR/cmul_karatsuba_tb.cpp"
export CMUL_KARATSUBA_TB_HPP="$CMUL_KARATSUBA_TB_DIR/cmul_karatsuba_tb.hpp"
export CMUL_KARATSUBA_GTEST_CPP="$CMUL_KARATSUBA_TB_DIR/cmul_karatsuba_gtest.cpp"
export CMUL_KARATSUBA_TB_SV="$CMUL_KARATSUBA_TB_DIR/cmul_karatsuba_tb.sv"
export CMUL_KARATSUBA_TB_REGRESSION_JSON="$CMUL_KARATSUBA_TB_DIR/cmul_karatsuba_tb_regression.json"

# Backward-compatible alias for simulation regression JSON
export CMUL_KARATSUBA_REGRESSION_JSON="$CMUL_KARATSUBA_TB_REGRESSION_JSON"

# Synthesis files
export CMUL_KARATSUBA_SYNTH_WRAPPER_V="$CMUL_KARATSUBA_SYNTH_DIR/cmul_karatsuba_wrapper_synth.v"
export CMUL_KARATSUBA_SYNTH_REGRESSION_JSON="$CMUL_KARATSUBA_SYNTH_DIR/cmul_karatsuba_synth_regression.json"

# Implementation files
export CMUL_KARATSUBA_IMPL_WRAPPER_V="$CMUL_KARATSUBA_IMPL_DIR/cmul_karatsuba_wrapper_impl.v"
export CMUL_KARATSUBA_IMPL_REGRESSION_JSON="$CMUL_KARATSUBA_IMPL_DIR/cmul_karatsuba_impl_regression.json"

# Flists
export CMUL_KARATSUBA_TB_FLIST="$CMUL_KARATSUBA_FLIST_DIR/cmul_karatsuba_tb.flist"
export CMUL_KARATSUBA_SYNTH_FLIST="$CMUL_KARATSUBA_FLIST_DIR/cmul_karatsuba_synth.flist"
export CMUL_KARATSUBA_IMPL_FLIST="$CMUL_KARATSUBA_FLIST_DIR/cmul_karatsuba_impl.flist"

