# fft1d_r2_sdf_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export FFT1D_R2_SDF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FFT1D_R2_SDF_VARS_SH="$FFT1D_R2_SDF_DIR/fft1d_r2_sdf_vars.sh"

# Build directories
export FFT1D_R2_SDF_BUILD_DIR="$FFT1D_R2_SDF_DIR/build"
export FFT1D_R2_SDF_SIM_BUILD_DIR="$FFT1D_R2_SDF_BUILD_DIR/simulation"
export FFT1D_R2_SDF_SYNTH_BUILD_DIR="$FFT1D_R2_SDF_BUILD_DIR/synthesis"
export FFT1D_R2_SDF_IMPL_BUILD_DIR="$FFT1D_R2_SDF_BUILD_DIR/implementation"

# Source directories
export FFT1D_R2_SDF_CPP_DIR="$FFT1D_R2_SDF_DIR/cpp"
export FFT1D_R2_SDF_FLIST_DIR="$FFT1D_R2_SDF_DIR/flist"
export FFT1D_R2_SDF_RTL_DIR="$FFT1D_R2_SDF_DIR/rtl"
export FFT1D_R2_SDF_TB_DIR="$FFT1D_R2_SDF_DIR/testbench"
export FFT1D_R2_SDF_SYNTH_DIR="$FFT1D_R2_SDF_DIR/synthesis"
export FFT1D_R2_SDF_IMPL_DIR="$FFT1D_R2_SDF_DIR/implementation"

# C++ model files
export FFT1D_R2_SDF_CPP_HPP="$FFT1D_R2_SDF_CPP_DIR/fft1d_r2_sdf.hpp"
export FFT1D_R2_SDF_CPP_CPP="$FFT1D_R2_SDF_CPP_DIR/fft1d_r2_sdf.cpp"

# RTL files
export FFT1D_R2_SDF_V="$FFT1D_R2_SDF_RTL_DIR/fft1d_r2_sdf.v"

# Testbench files
export FFT1D_R2_SDF_TB_CPP="$FFT1D_R2_SDF_TB_DIR/fft1d_r2_sdf_tb.cpp"
export FFT1D_R2_SDF_TB_HPP="$FFT1D_R2_SDF_TB_DIR/fft1d_r2_sdf_tb.hpp"
export FFT1D_R2_SDF_TB_SV="$FFT1D_R2_SDF_TB_DIR/fft1d_r2_sdf_tb.sv"
export FFT1D_R2_SDF_TB_REGRESSION_JSON="$FFT1D_R2_SDF_TB_DIR/fft1d_r2_sdf_tb_regression.json"
export FFT1D_R2_SDF_GTEST_CPP="$FFT1D_R2_SDF/fft1d_r2_sdf_gtest.cpp"

# Backward-compatible alias for simulation regression JSON
export FFT1D_R2_SDF_REGRESSION_JSON="$FFT1D_R2_SDF_TB_REGRESSION_JSON"

# Synthesis files
export FFT1D_R2_SDF_SYNTH_WRAPPER_V="$FFT1D_R2_SDF_SYNTH_DIR/fft1d_r2_sdf_wrapper_synth.v"
export FFT1D_R2_SDF_SYNTH_REGRESSION_JSON="$FFT1D_R2_SDF_SYNTH_DIR/fft1d_r2_sdf_synth_regression.json"

# Implementation files
export FFT1D_R2_SDF_IMPL_WRAPPER_V="$FFT1D_R2_SDF_IMPL_DIR/fft1d_r2_sdf_wrapper_impl.v"
export FFT1D_R2_SDF_IMPL_REGRESSION_JSON="$FFT1D_R2_SDF_IMPL_DIR/fft1d_r2_sdf_impl_regression.json"

# Flists
export FFT1D_R2_SDF_TB_FLIST="$FFT1D_R2_SDF_FLIST_DIR/fft1d_r2_sdf_tb.flist"
export FFT1D_R2_SDF_SYNTH_FLIST="$FFT1D_R2_SDF_FLIST_DIR/fft1d_r2_sdf_synth.flist"
export FFT1D_R2_SDF_IMPL_FLIST="$FFT1D_R2_SDF_FLIST_DIR/fft1d_r2_sdf_impl.flist"

