# run_synth.tcl
#
# Usage:
# vivado -mode batch -notrace -source $PROJECT_ROOT/scripts/run_synth.tcl \
#   -tclargs <case_dir> <launch_dir> PART_NAME=... CLOCK_PERIOD_NS=... [DEFINES...]

proc fail {msg} {
    puts stderr "\[run_synth.tcl\] ERROR: $msg"
    exit 1
}

proc log_msg {msg} {
    puts "\[run_synth.tcl\] $msg"
}

proc require_env {name} {
    if {![info exists ::env($name)]} {
        fail "environment variable not defined: $name"
    }

    return $::env($name)
}

proc require_file {path label} {
    if {![file exists $path]} {
        fail "missing $label: $path"
    }
}

proc require_dir {path label} {
    if {![file isdirectory $path]} {
        fail "missing $label: $path"
    }
}

proc module_prefix {module_name} {
    return [string toupper $module_name]
}

proc detect_module_from_dir {modules_root launch_dir} {
    set dir_real     [file normalize $launch_dir]
    set modules_real [file normalize $modules_root]
    set prefix "${modules_real}/"

    if {[string first $prefix $dir_real] != 0} {
        fail "launch directory is not inside MODULES_ROOT. launch_dir=$dir_real MODULES_ROOT=$modules_real"
    }

    set rel_path [string range $dir_real [string length $prefix] end]
    set parts [file split $rel_path]

    if {[llength $parts] < 1} {
        fail "could not detect module name"
    }

    set module_name [lindex $parts 0]

    if {![file isdirectory [file join $modules_root $module_name]]} {
        fail "detected module directory does not exist: [file join $modules_root $module_name]"
    }

    return $module_name
}

proc is_positive_number {value} {
    if {![string is double -strict $value]} {
        return 0
    }

    return [expr {$value > 0.0}]
}

proc is_nonnegative_number {value} {
    if {![string is double -strict $value]} {
        return 0
    }

    return [expr {$value >= 0.0}]
}

proc parse_flist {flist_path} {
    set incdirs {}
    set files {}

    set fd [open $flist_path "r"]

    while {[gets $fd line] >= 0} {
        set line [string trim $line]

        if {$line eq ""} {
            continue
        }

        if {[string match "#*" $line]} {
            continue
        }

        if {[regexp {^-i[ \t]+(.+)$} $line -> incdir]} {
            lappend incdirs [file normalize $incdir]
            continue
        }

        if {[regexp {^\+incdir\+(.+)$} $line -> incdir]} {
            lappend incdirs [file normalize $incdir]
            continue
        }

        lappend files [file normalize $line]
    }

    close $fd

    foreach incdir $incdirs {
        require_dir $incdir "include directory"
    }

    foreach file $files {
        require_file $file "RTL source file"
    }

    return [list $incdirs $files]
}

proc run_tcl_cmd {label cmd} {
    log_msg $label
    log_msg "cmd: $cmd"

    if {[catch {uplevel 1 $cmd} result]} {
        puts stderr "\[run_synth.tcl\] ERROR: $label failed"

        if {$result ne ""} {
            puts stderr $result
        }

        exit 1
    }
}

proc write_clock_xdc {xdc_file clock_period_ns clock_uncertainty_ns} {
    file mkdir [file dirname $xdc_file]

    set fd [open $xdc_file "w"]

    puts $fd "# Autogenerated by run_synth.tcl"
    puts $fd "# Do not edit manually."
    puts $fd ""
    puts $fd "create_clock -name {i_clock} -period $clock_period_ns \[get_ports {i_clock}\]"

    if {$clock_uncertainty_ns ne ""} {
        puts $fd "set_clock_uncertainty $clock_uncertainty_ns \[get_clocks {i_clock}\]"
    }

    close $fd
}

proc get_path_slack {delay_type} {
    set paths [get_timing_paths -quiet -max_paths 1 -delay_type $delay_type]

    if {[llength $paths] == 0} {
        return "NA"
    }

    return [get_property SLACK [lindex $paths 0]]
}

proc is_number {value} {
    return [string is double -strict $value]
}

proc write_metrics_report {metrics_file clock_period_ns clock_freq_mhz clock_uncertainty_ns} {
    file mkdir [file dirname $metrics_file]

    set wns [get_path_slack "max"]
    set whs [get_path_slack "min"]

    set est_fmax_mhz "NA"

    if {[is_number $wns]} {
        set path_delay_ns [expr {$clock_period_ns - $wns}]

        if {$path_delay_ns > 0.0} {
            set est_fmax_mhz [format "%.6f" [expr {1000.0 / $path_delay_ns}]]
        }
    }

    set fd [open $metrics_file "w"]

    puts $fd "CLOCK_PERIOD_NS=$clock_period_ns"

    if {$clock_freq_mhz ne ""} {
        puts $fd "CLOCK_FREQ_MHZ=$clock_freq_mhz"
    }

    if {$clock_uncertainty_ns ne ""} {
        puts $fd "CLOCK_UNCERTAINTY_NS=$clock_uncertainty_ns"
    }

    puts $fd "WNS_NS=$wns"
    puts $fd "WHS_NS=$whs"
    puts $fd "EST_FMAX_MHZ=$est_fmax_mhz"

    close $fd
}

if {[llength $argv] < 2} {
    fail "usage: run_synth.tcl <case_dir> <launch_dir> PART_NAME=... CLOCK_PERIOD_NS=... [DEFINES...]"
}

set project_root [require_env PROJECT_ROOT]
set modules_root [require_env MODULES_ROOT]

set case_dir   [lindex $argv 0]
set launch_dir [lindex $argv 1]

set module_name [detect_module_from_dir $modules_root $launch_dir]
set prefix      [module_prefix $module_name]

set synth_flist_var "${prefix}_SYNTH_FLIST"
set synth_flist     [require_env $synth_flist_var]

require_file $synth_flist "synth flist"

if {[file pathtype $case_dir] ne "absolute"} {
    set module_dir [file normalize [file join $modules_root $module_name]]
    set case_dir [file normalize [file join $module_dir $case_dir]]
} else {
    set case_dir [file normalize $case_dir]
}

set part_name ""
set clock_period_ns ""
set clock_freq_mhz ""
set clock_uncertainty_ns ""

set rtl_defines {}

foreach arg [lrange $argv 2 end] {
    if {![regexp {^([^=]+)=(.*)$} $arg -> key value]} {
        fail "invalid argument: $arg. Expected KEY=VALUE."
    }

    switch -- $key {
        "PART_NAME" {
            set part_name $value
        }
        "CLOCK_PERIOD_NS" {
            set clock_period_ns $value
        }
        "CLOCK_FREQ_MHZ" {
            set clock_freq_mhz $value
        }
        "CLOCK_UNCERTAINTY_NS" {
            set clock_uncertainty_ns $value
        }
        default {
            lappend rtl_defines "${key}=${value}"
        }
    }
}

if {$part_name eq ""} {
    fail "PART_NAME is required"
}

if {$clock_period_ns eq "" && $clock_freq_mhz eq ""} {
    fail "define either CLOCK_PERIOD_NS or CLOCK_FREQ_MHZ"
}

if {$clock_period_ns ne "" && $clock_freq_mhz ne ""} {
    fail "define only one of CLOCK_PERIOD_NS or CLOCK_FREQ_MHZ"
}

if {$clock_freq_mhz ne ""} {
    if {![is_positive_number $clock_freq_mhz]} {
        fail "invalid CLOCK_FREQ_MHZ=$clock_freq_mhz"
    }

    set clock_period_ns [format "%.6f" [expr {1000.0 / $clock_freq_mhz}]]
}

if {![is_positive_number $clock_period_ns]} {
    fail "invalid CLOCK_PERIOD_NS=$clock_period_ns"
}

if {$clock_uncertainty_ns ne ""} {
    if {![is_nonnegative_number $clock_uncertainty_ns]} {
        fail "invalid CLOCK_UNCERTAINTY_NS=$clock_uncertainty_ns"
    }
}

set top_name "${module_name}_wrapper_synth"

set constraints_dir [file join $case_dir "constraints"]
set reports_dir     [file join $case_dir "reports"]
set checkpoints_dir [file join $case_dir "checkpoints"]
set work_dir        [file join $case_dir "synthesis" "work"]

file mkdir $constraints_dir
file mkdir $reports_dir
file mkdir $checkpoints_dir
file mkdir $work_dir

set synth_xdc          [file join $constraints_dir "synth.xdc"]
set utilization_rpt    [file join $reports_dir "utilization_synth.rpt"]
set timing_summary_rpt [file join $reports_dir "timing_summary_synth.rpt"]
set metrics_rpt        [file join $reports_dir "synth_metrics.rpt"]
set checkpoint_file    [file join $checkpoints_dir "synth.dcp"]

set parsed_flist [parse_flist $synth_flist]
set incdirs [lindex $parsed_flist 0]
set files   [lindex $parsed_flist 1]

write_clock_xdc $synth_xdc $clock_period_ns $clock_uncertainty_ns

log_msg "module        : $module_name"
log_msg "top           : $top_name"
log_msg "part          : $part_name"
log_msg "case_dir      : $case_dir"
log_msg "flist         : $synth_flist"
log_msg "xdc           : $synth_xdc"
log_msg "period_ns     : $clock_period_ns"

if {$clock_freq_mhz ne ""} {
    log_msg "freq_mhz      : $clock_freq_mhz"
}

if {$clock_uncertainty_ns ne ""} {
    log_msg "uncertainty   : $clock_uncertainty_ns"
}

if {[llength $rtl_defines] > 0} {
    log_msg "defines       : $rtl_defines"
}

cd $work_dir

run_tcl_cmd "create_project" [list create_project -in_memory -part $part_name]

run_tcl_cmd "add_files" [concat [list add_files -norecurse] $files]

foreach src_file $files {
    set file_obj [get_files -quiet $src_file]

    if {[llength $file_obj] > 0} {
        set_property file_type SystemVerilog $file_obj
    }
}

if {[llength $incdirs] > 0} {
    set_property include_dirs $incdirs [current_fileset]
}

if {[llength $rtl_defines] > 0} {
    set_property verilog_define $rtl_defines [current_fileset]
}

set_property top $top_name [current_fileset]

run_tcl_cmd "read_xdc" [list read_xdc $synth_xdc]
run_tcl_cmd "update_compile_order" [list update_compile_order -fileset sources_1]
run_tcl_cmd "synth_design" [list synth_design -top $top_name -part $part_name]

run_tcl_cmd "report_utilization" [list report_utilization -file $utilization_rpt]
run_tcl_cmd "report_timing_summary" [list report_timing_summary -file $timing_summary_rpt]

write_metrics_report $metrics_rpt $clock_period_ns $clock_freq_mhz $clock_uncertainty_ns

run_tcl_cmd "write_checkpoint" [list write_checkpoint -force $checkpoint_file]

log_msg "utilization   : $utilization_rpt"
log_msg "timing        : $timing_summary_rpt"
log_msg "metrics       : $metrics_rpt"
log_msg "checkpoint    : $checkpoint_file"
log_msg "done"