# btfly_sdf_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export BTFLY_SDF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export BTFLY_SDF_VARS_SH="$BTFLY_SDF_DIR/btfly_sdf_vars.sh"

# Build directories
export BTFLY_SDF_BUILD_DIR="$BTFLY_SDF_DIR/build"
export BTFLY_SDF_SIM_BUILD_DIR="$BTFLY_SDF_BUILD_DIR/simulation"
export BTFLY_SDF_SYNTH_BUILD_DIR="$BTFLY_SDF_BUILD_DIR/synthesis"
export BTFLY_SDF_IMPL_BUILD_DIR="$BTFLY_SDF_BUILD_DIR/implementation"

# Source directories
export BTFLY_SDF_CPP_DIR="$BTFLY_SDF_DIR/cpp"
export BTFLY_SDF_FLIST_DIR="$BTFLY_SDF_DIR/flist"
export BTFLY_SDF_RTL_DIR="$BTFLY_SDF_DIR/rtl"
export BTFLY_SDF_TB_DIR="$BTFLY_SDF_DIR/testbench"
export BTFLY_SDF_SYNTH_DIR="$BTFLY_SDF_DIR/synthesis"
export BTFLY_SDF_IMPL_DIR="$BTFLY_SDF_DIR/implementation"

# C++ model files
export BTFLY_SDF_CPP_HPP="$BTFLY_SDF_CPP_DIR/btfly_sdf.hpp"
export BTFLY_SDF_CPP_CPP="$BTFLY_SDF_CPP_DIR/btfly_sdf.cpp"

# RTL files
export BTFLY_SDF_V="$BTFLY_SDF_RTL_DIR/btfly_sdf.v"

# Testbench files
export BTFLY_SDF_TB_CPP="$BTFLY_SDF_TB_DIR/btfly_sdf_tb.cpp"
export BTFLY_SDF_TB_HPP="$BTFLY_SDF_TB_DIR/btfly_sdf_tb.hpp"
export BTFLY_SDF_TB_SV="$BTFLY_SDF_TB_DIR/btfly_sdf_tb.sv"
export BTFLY_SDF_TB_REGRESSION_JSON="$BTFLY_SDF_TB_DIR/btfly_sdf_tb_regression.json"
export BTFLY_SDF_GTEST_CPP="$BTFLY_SDF/btfly_sdf_gtest.cpp"

# Backward-compatible alias for simulation regression JSON
export BTFLY_SDF_REGRESSION_JSON="$BTFLY_SDF_TB_REGRESSION_JSON"

# Synthesis files
export BTFLY_SDF_SYNTH_WRAPPER_V="$BTFLY_SDF_SYNTH_DIR/btfly_sdf_wrapper_synth.v"
export BTFLY_SDF_SYNTH_REGRESSION_JSON="$BTFLY_SDF_SYNTH_DIR/btfly_sdf_synth_regression.json"

# Implementation files
export BTFLY_SDF_IMPL_WRAPPER_V="$BTFLY_SDF_IMPL_DIR/btfly_sdf_wrapper_impl.v"
export BTFLY_SDF_IMPL_REGRESSION_JSON="$BTFLY_SDF_IMPL_DIR/btfly_sdf_impl_regression.json"

# Flists
export BTFLY_SDF_TB_FLIST="$BTFLY_SDF_FLIST_DIR/btfly_sdf_tb.flist"
export BTFLY_SDF_SYNTH_FLIST="$BTFLY_SDF_FLIST_DIR/btfly_sdf_synth.flist"
export BTFLY_SDF_IMPL_FLIST="$BTFLY_SDF_FLIST_DIR/btfly_sdf_impl.flist"

