# fft1d_r2_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export FFT1D_R2_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FFT1D_R2_VARS_SH="$FFT1D_R2_DIR/fft1d_r2_vars.sh"

# Build directories
export FFT1D_R2_BUILD_DIR="$FFT1D_R2_DIR/build"
export FFT1D_R2_SIM_BUILD_DIR="$FFT1D_R2_BUILD_DIR/simulation"
export FFT1D_R2_SYNTH_BUILD_DIR="$FFT1D_R2_BUILD_DIR/synthesis"
export FFT1D_R2_IMPL_BUILD_DIR="$FFT1D_R2_BUILD_DIR/implementation"

# Source directories
export FFT1D_R2_CPP_DIR="$FFT1D_R2_DIR/cpp"
export FFT1D_R2_FLIST_DIR="$FFT1D_R2_DIR/flist"
export FFT1D_R2_RTL_DIR="$FFT1D_R2_DIR/rtl"
export FFT1D_R2_TB_DIR="$FFT1D_R2_DIR/testbench"
export FFT1D_R2_SYNTH_DIR="$FFT1D_R2_DIR/synthesis"
export FFT1D_R2_IMPL_DIR="$FFT1D_R2_DIR/implementation"

# C++ model files
export FFT1D_R2_CPP_HPP="$FFT1D_R2_CPP_DIR/fft1d_r2.hpp"
export FFT1D_R2_CPP_CPP="$FFT1D_R2_CPP_DIR/fft1d_r2.cpp"

# RTL files
export FFT1D_R2_V="$FFT1D_R2_RTL_DIR/fft1d_r2.v"

# Testbench files
export FFT1D_R2_TB_CPP="$FFT1D_R2_TB_DIR/fft1d_r2_tb.cpp"
export FFT1D_R2_TB_HPP="$FFT1D_R2_TB_DIR/fft1d_r2_tb.hpp"
export FFT1D_R2_TB_SV="$FFT1D_R2_TB_DIR/fft1d_r2_tb.sv"
export FFT1D_R2_TB_REGRESSION_JSON="$FFT1D_R2_TB_DIR/fft1d_r2_tb_regression.json"
export FFT1D_R2_GTEST_CPP="$FFT1D_R2_TB_DIR/fft1d_r2_gtest.cpp"

# Backward-compatible alias for simulation regression JSON
export FFT1D_R2_REGRESSION_JSON="$FFT1D_R2_TB_REGRESSION_JSON"

# Synthesis files
export FFT1D_R2_SYNTH_WRAPPER_V="$FFT1D_R2_SYNTH_DIR/fft1d_r2_wrapper_synth.v"
export FFT1D_R2_SYNTH_REGRESSION_JSON="$FFT1D_R2_SYNTH_DIR/fft1d_r2_synth_regression.json"

# Implementation files
export FFT1D_R2_IMPL_WRAPPER_V="$FFT1D_R2_IMPL_DIR/fft1d_r2_wrapper_impl.v"
export FFT1D_R2_IMPL_REGRESSION_JSON="$FFT1D_R2_IMPL_DIR/fft1d_r2_impl_regression.json"

# Flists
export FFT1D_R2_TB_FLIST="$FFT1D_R2_FLIST_DIR/fft1d_r2_tb.flist"
export FFT1D_R2_SYNTH_FLIST="$FFT1D_R2_FLIST_DIR/fft1d_r2_synth.flist"
export FFT1D_R2_IMPL_FLIST="$FFT1D_R2_FLIST_DIR/fft1d_r2_impl.flist"

