# delay_line_vars.sh
# This file is autogenerated by create_module / refresh_module_vars.

export DELAY_LINE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export DELAY_LINE_VARS_SH="$DELAY_LINE_DIR/delay_line_vars.sh"

# Build directories
export DELAY_LINE_BUILD_DIR="$DELAY_LINE_DIR/build"
export DELAY_LINE_SIM_BUILD_DIR="$DELAY_LINE_BUILD_DIR/simulation"
export DELAY_LINE_SYNTH_BUILD_DIR="$DELAY_LINE_BUILD_DIR/synthesis"
export DELAY_LINE_IMPL_BUILD_DIR="$DELAY_LINE_BUILD_DIR/implementation"

# Source directories
export DELAY_LINE_CPP_DIR="$DELAY_LINE_DIR/cpp"
export DELAY_LINE_FLIST_DIR="$DELAY_LINE_DIR/flist"
export DELAY_LINE_RTL_DIR="$DELAY_LINE_DIR/rtl"
export DELAY_LINE_TB_DIR="$DELAY_LINE_DIR/testbench"
export DELAY_LINE_SYNTH_DIR="$DELAY_LINE_DIR/synthesis"
export DELAY_LINE_IMPL_DIR="$DELAY_LINE_DIR/implementation"

# C++ model files
export DELAY_LINE_CPP_HPP="$DELAY_LINE_CPP_DIR/delay_line.hpp"
export DELAY_LINE_CPP_CPP="$DELAY_LINE_CPP_DIR/delay_line.cpp"

# RTL files
export DELAY_LINE_V="$DELAY_LINE_RTL_DIR/delay_line.v"

# Testbench files
export DELAY_LINE_TB_CPP="$DELAY_LINE_TB_DIR/delay_line_tb.cpp"
export DELAY_LINE_TB_HPP="$DELAY_LINE_TB_DIR/delay_line_tb.hpp"
export DELAY_LINE_TB_SV="$DELAY_LINE_TB_DIR/delay_line_tb.sv"
export DELAY_LINE_TB_REGRESSION_JSON="$DELAY_LINE_TB_DIR/delay_line_tb_regression.json"
export DELAY_LINE_GTEST_CPP="$DELAY_LINE/delay_line_gtest.cpp"

# Backward-compatible alias for simulation regression JSON
export DELAY_LINE_REGRESSION_JSON="$DELAY_LINE_TB_REGRESSION_JSON"

# Synthesis files
export DELAY_LINE_SYNTH_WRAPPER_V="$DELAY_LINE_SYNTH_DIR/delay_line_wrapper_synth.v"
export DELAY_LINE_SYNTH_REGRESSION_JSON="$DELAY_LINE_SYNTH_DIR/delay_line_synth_regression.json"

# Implementation files
export DELAY_LINE_IMPL_WRAPPER_V="$DELAY_LINE_IMPL_DIR/delay_line_wrapper_impl.v"
export DELAY_LINE_IMPL_REGRESSION_JSON="$DELAY_LINE_IMPL_DIR/delay_line_impl_regression.json"

# Flists
export DELAY_LINE_TB_FLIST="$DELAY_LINE_FLIST_DIR/delay_line_tb.flist"
export DELAY_LINE_SYNTH_FLIST="$DELAY_LINE_FLIST_DIR/delay_line_synth.flist"
export DELAY_LINE_IMPL_FLIST="$DELAY_LINE_FLIST_DIR/delay_line_impl.flist"

